 

name: check
on:

  workflow_dispatch:
  repository_dispatch:
       type: [build]

env:
     version: ${{ github.event.client_payload.version }}
jobs:
 check:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: touch my_file.txt
      - name: display 
        run: |
           pwd
           ls
      - uses: szenius/set-timezone@v1.0
        with:
         timezoneLinux: "Asia/Singapore"
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Build_${{ env.version }}
          release_name: Build_${{ env.version }}_${{ TIME }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: meeDamian/github-release@2.0
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         tag: Build_${{ env.version }}
         name: Build_${{ env.version }}_${{ TIME }}
         allow_override: true
         files: my_file.txt

      
