name: check new
on:

  workflow_dispatch:
  repository_dispatch:
       types: [Test_Build]

env:
     version: ${{ github.event.client_payload.version }}
jobs:
 check:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: create a file 
        run: |
          touch my_file.txt
          Name=$(date +ON-%u-%h-%y-AT-%I.%M.%S.%p)
          echo "MY_DATE= $Name" >> $GITHUB_ENV
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
         name: Build_${{ env.MY_DATE }}
         path: my_file.txt
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: Tag_${{ env.version }}
          release_name: Release_${{ env.version }}
          body: TODO
          draft: true
          prerelease: false
  
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Build_${{ env.MY_DATE }}
          path: ./
      - name: Zip artifact for deployment
        run: zip my_file.zip ./my_file.txt -r
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload the release asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: https://uploads.github.com/repos/mangeshpatiln/test/releases/75758962/assets{?name,label}
         asset_path: ./
         asset_name: my_file.zip
         asset_content_type: application/zip
      
 
    # - name: Upload Release Asset
    #   uses: meeDamian/github-release@2.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     tag: Tag_${{ env.version }}
    #     name: Release_${{ env.version }}
    #     allow_override: true
    #     files: my_file.txt
