name: check
on:

  workflow_dispatch:

env:
     version: ${{ github.event.client_payload.version }}
jobs:
 check:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: touch my_file.txt
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: Tag_name
          release_name: Release_name
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./my_file.txt"]'
    

