name: get current time
on: 
   workflow_dispatch:
jobs:
  # Deploy Process
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone
      uses: szenius/set-timezone@v1.0
      with:
       timezoneLinux: "Asia/Mumbai"
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
      run: echo $TIME
