name: delete artifact

on: 
 workflow_dispatch:
# schedule:
 # - cron: '*/5 * * * *'

jobs:
  delete:
    runs-on: ubuntu-latest
    #needs: build
    steps:
   # - name: Sleep for 180 seconds
   #   uses: kibertoad/wait-action@1.0.1
   #   with:
   #     time: '180s'
   # - name: delete artifact
   #   uses: geekyeggo/delete-artifact@v1
    - uses: kolpav/purge-artifacts-action@v1
      with:
          token: $
          expire-in: 7days

