

name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: demo.txt
        path: C:\Users\MangeshPatil\
    - name: Deploy backend
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      with:
        host: ${{ secrets.HOST }} # "example.com"
        port: ${{ secrets.SSH_PORT }} # 22
        username: ${{ secrets.USERNAME }} # "user"
        password: ${{ secrets.PASSWORD }} # "password"
        files: |
          C:\Users\MangeshPatil\demo.txt
        remote-path: "/home/mpatil/new/demo.txt"
        clean: true
