name: remote ssh command
on: 
 workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: test.datsseers.in
        username: mpatil
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: whoami
