name: Command via SSH

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: 192.168.0.228
          username: mpatil
          password: mp@123DataSeer$
          privateKey: ${{ secrets.PRIVATE_KEY}}
        env:
          CI: true
