

name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 
    - name: Deploy backend
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      with:
        host: ${{ secrets.HOST }} # "example.com"
        port: ${{ secrets.SSH_PORT }} # 22
        username: ${{ secrets.USER_NAME }} # "user"
        password: ${{ secrets.PASSWORD }} # "password"
        files: |
          C:\Users\MangeshPatil\Desktop\demo.txt
        remote-path: "/home/mpatil/new/demo.txt"
        clean: true
