name: Command via SSH

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
                   # mail server settings
        server_address: smtp.365.com
        server_port: 465
              # user credentials
        username: mpatil@dataseers.in
        password: Maxparron@123
                  # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
                # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
                 # comma-separated string, send email to
        to: slondhe@dataseers.in
                 # from email name
        from: Mangesh Patil
