

name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy backend
      uses: ilCollez/ssh-scp-deploy@v1.1.0
      with:
        host: ${{ secrets.HOST }} # "example.com"
        port: ${{ secrets.SSH_PORT }} # 22
        username: ${{ secrets.USERNAME }} # "user"
        password: ${{ secrets.PASSWORD }} # "password"
        files: |
          demo*
        remote-path: "/"
        clean: true
