name: asigning date as a name
# This workflow is triggered at a scheduled interval of every 30 minutes
on:
    workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
     - name: create a file
       run: |
         Name=Build
         mkdir -p ~/new/
         cd ~/new
         mkdir ~/new/$Name
         
     - name: 'Upload Artifact' 
       uses: actions/upload-artifact@v3
       with:
        name: $Name
        path: ~/new/*
