name: asigning date as a name
# This workflow is triggered at a scheduled interval of every 30 minutes
on:
    workflow_dispatch:
defaults:
  run:
    working-directory: web

jobs:
  push:
    runs-on: ubuntu-latest
    env:
          Name: date '+%F_%H:%M:%S'
    steps:
     - name: create a file
       run: touch $Name
     - name: 'Upload Artifact'
       env: 
         new_path: ls 
       uses: actions/upload-artifact@v3
       with:
        name: $Name
        path: web
