name: asigning date as a name
# This workflow is triggered at a scheduled interval of every 30 minutes
on:
    workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
     - name: create a file
       run: |
         Name=$(date '+%F%H%M%S')
         rm -rf *
         mkdir $Name
         N=$(ls)
         echo "$N" >> $GITHUB_ENV
       shell: bash

     - name: 'Upload Artifact' 
       uses: actions/upload-artifact@v3
       with:
        name: $GITHUB_ENV
        path: $GITHUB_ENV
