name: asigning date as a name
# This workflow is triggered at a scheduled interval of every 30 minutes
on:
    workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
          Name: date '+%F_%H:%M:%S'
  
    steps:
      - name: create a file
        run:  touch $Name.txt
 
      - name: 'Upload Artifact'
        env: 
         new_path: ls 
        uses: actions/upload-artifact@v3
        with:
         name: $Name
         path: /home/runner/work/test/tset
