name: email notification try

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Send mail
       uses: dawidd6/action-send-mail@v3
       with:
          server_address: smtp.gmail.com
          server_port: 465
          username: mpatil@dataseers.in
          password: Parronmax@123 
          subject: Github Actions job result
          to: slondhe@dataseers.in
          from: Mangesh Patil
          secure: true
          body: Build job of ${{github.repository}} completed successfully!
 
 
