name: Scheduled Ping
# This workflow is triggered at a scheduled interval of every 30 minutes
on:
    workflow_dispatch:

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: http://test.datasets.in/
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
