
name: repo dispatch
on:
  repository_dispatch:
      type: [build]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: message
       run: echo "My name is ${{ github.event.client_payload.one}} and i am working for ${{ github.event.client_payload.two}}"
