name: ssh_connection
on:
  push:
    branches: []
   
jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh
      uses:  appleboy/ssh-action@v1.0.3
      with:
        host: 192.168.26.19
        username: jenkins
        key: ${{ secrets.SECRETE_KEY }}
        port: 22
        script: |
            ls -ltr
            pwd
            hostname
 
