name: ssh_connection
on:
  push:
    branches: []
   
jobs:
  snyk-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh
      uses: appleboy/ssh-sction@master
      with:
        host: 192.168.26.19
        key: ${{secrets.SECRETE}}
        port: 22
        script: |
            ls -ltr
            pwd
            hostname
 
