name: ssh_connection
on:
  push:
    branches: []
   
jobs:
  conn_server:
    name: 'conn_server'
    environment: ppm_prod    
    runs-on: ubuntu-latest
    steps:
      - name: conn_step1
        uses: appleboy/ssh-action@master 
        with:
          host: 192.168.26.19
          username: jenkins
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            echo "connection complete : "
            pwd
            echo `hostname` 
            exit
