name: test ssh and scp
on:
  workflow_dispatch:
 
jobs:
  deploy-backend:
    runs-on: ubuntu-20.04
    steps:
     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
       with:
        key: ${{ secrets.PRIVATE_KEY }} 
