name: remote ssh command
on: 
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: sudo ufw allow ssh
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: test.dataseers.in
        username: mpatil
        password: mp@123DataSeer$
        port: 443
        script: |
             whoami
             cd /home/mpatil/new
             touch new.txt
