name: check
on:

  workflow_dispatch:
  push: 
    branches: [main]
    paths: [package.json]
  pull_request:
    branches: [main]
env:
     version: ${{ github.event.client_payload.version }}

jobs:
  snyk-analysis:
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: version
      run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
       draft: false
       prerelease: false
       release_name: ${{ steps.version.outputs.version }}
       tag_name: ${{ github.ref }}
       body_path: CHANGELOG.md
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
