name: remote ssh command
on: 
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 49.248.125.106
        username: mpatil
        password: mp@123DataSeer$
        port: 22
        script: |
             whoami
             cd /home/mpatil/new
             touch new.txt
