name: remote ssh command
on: 
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.0.228
        username: mpatil
        password: mp@123DataSeer$
        app_port: 22
        script: whoami
