name: TRY2
on: 
   workflow_dispatch:
jobs:
  # Deploy Process
  deploy:
    runs-on: ubuntu-latest
    steps:   
    - name: Copy single file to remote
      uses: appleboy/ssh-action@master
      with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: test.dataseers.in
          username: mpatil
          port: 22
          script: |
            ls -la
