name: TRY with guthub action scp
on: 
   workflow_dispatch:
jobs:
  # Deploy Process
  deploy:
    runs-on: ubuntu-18.04 
    steps:   
     - name: Copy single file to remote
       uses: garygrossgarten/github-action-scp@release
       with:
          local: /mangeshpatiln/test/blob/main/demo.txt
          remote: /home/mpatil/new/demo.txt
          host: test.dataseers.in
          username: mpatil
          password: mp@123DataSeer$
