name: deploy_create realease
on:
  
    workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: creating release
       uses: actions/create-release@v1
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       with:
          tag_name: Tag_name
          release_name: Release_name
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
 
