name: upload artifact

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: create a file 
       run: touch my_file.txt
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
        name: build
        path: my_file.txt
     - name: upload artifact for backup
       uses: actions/upload-artifact@v3
       with:
        name: my-artifact
        path: my_file.txt

name: upload artifact

on: 
 workflow_dispatch:

jobs:   
  delete:
    runs-on: ubuntu-latest
    #needs: build
    steps:
    - name: Sleep for 180 seconds
      uses: kibertoad/wait-action@1.0.1
      with:
        time: '180s'
    - name: delete artifact
      uses: geekyeggo/delete-artifact@v1
      with:
          name: build
  
    
