name: upload artifact

on: 
 workflow_dispatch:
 schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: create a file 
       if: github.eventname == 'workflow_dispatch'
       run: touch my_file.txt
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
        name: build
        path: my_file.txt
     - name: upload artifact for backup
       uses: actions/upload-artifact@v3
       with:
        name: my-artifact
        path: my_file.txt
 
  delete:
    runs-on: ubuntu-latest
    if: github.eventname == 'schedule'
   # needs: build
    steps:
    - name: Sleep for 180 seconds
      uses: kibertoad/wait-action@1.0.1
      with:
        time: '5m'
    - name: delete artifact
      uses: geekyeggo/delete-artifact@v1
      with:
          name: build
 

 
  
    
