name: upload artifact

on: 
 workflow_dispatch:
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: create a file 
       run: touch my_file.txt
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
        name: build
        path: my_file.txt
    
 
 
 

 
  
    
