name: upload artifact

on: 
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: create a file 
       run: |
          touch my_file.txt
          Name=$(date '+%F%H%M%S')
          echo "$Name" >> $GITHUB_ENV
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
         name: $GITHUB_ENV
         path: my_file.txt
    
 
 
 

 
  
    
