name: upload artifact

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - run: date +"%m-%d-%Y" > name.txt
       env:
          Name: cat Name.txt
     - run: echo"$Name"
     - name: create a file 
       run: touch my_file.txt
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
        name: build_$Name
        path: my_file.txt
    
 
 
 

 
  
    
