name: upload artifact

on: 
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: create a file 
       run: |
          touch my_file.txt
          Name=$(date +ON-%u-%h-%y-AT-%I.%M.%S.%p)
          echo "MY_DATE= $Name" >> $GITHUB_ENV
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
         name: Build_${{ env.MY_DATE }}
         path: my_file.txt
    
 
 
 

 
  
    
