name: upload artifact

on: 
 workflow_dispatch:
env:
    Name: $ (date +"%m-%d-%Y")
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: create a file 
       run: touch my_file.txt
     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v3
       with:
        name: "build_ $Name"
        path: my_file.txt
    
 
 
 

 
  
    
